[package]
name = "aws-experiments"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]
edition = "2018"

[dependencies]
aws-config = "0.11.0"
aws-sdk-lambda = "0.11.0"
tokio = { version = "1", features = ["full"] }
